### ISSUE TITLE
Any issue with including in referenced assemblies as well as startup web project?

### ISSUE THREAD

**Issue by ryno1234** [ninject/Ninject.Web.Common#24]
I'm currently using this (along with Ninject.Web.Mvc) in my project, however I have a "Services" project which is used to provided service implementations but is a standard "Code" project (i.e. not an "MVC" project).

Is there any issue with my MVC project referencing other project assemblies that also contain Ninject.Web.Common? I realize there is bootstrapping and other boilerplate code that I want to make sure is not firing off multiple unnecessarily. 

Thanks Remo!

**Comment by scott-xu** [comment]
Your startup project will have only one Ninject.Web.Mvc no matter how many same references your "child" , "grandchild" projects have.
