### ISSUE TITLE
Problem with Ninject.Web.Common.Xml NuGet Package

### ISSUE THREAD

**Issue by geoffwc** [ninject/Ninject.Web.Common#25]
Just installed Ninject.Web.Common.Xml and found the packages\Ninject.Web.Common.Xml directory has no lib folder so contains no binaries. Because of this the reference is not added to project and the assembly can't be used.

I cloned the repo and built it locally to get round the issue, but would be nice to have the NuGet package working!

Thanks

**Comment by scott-xu** [comment]
Please try https://www.nuget.org/packages/Ninject.Web.Common.Xml/3.2.4-unstable-002

**Comment by geoffwc** [comment]
Great, works nicely. Thanks
