### ISSUE TITLE
NinjectWebCommon.cs not added to project

### ISSUE THREAD

**Issue by rkapka** [ninject/Ninject.Web.Common#35]
I am developing an MVC 5 application targeting .NET Framework 4.6.1 using Visual Studio 2017. Installing version 3.3.0 of the _Ninject.Web.Common_ package results in the `NinjectWebCommon.cs` file not being added to the project (the file is not present in the _App_Start_ folder either). Downgrading the package to 3.2.3 solves the issue.

**Comment by htuomas** [comment]
I had the same problem developing WebAPI 2 app - didn't get the NinjectWebCommon.cs file. After downgrading all Ninject nugets to 3.2.2 I got the file, but then I got an exception about not finding the Ninject 3.3.x assemblies when starting the app. Then I updated back to 3.3.x and added `using Ninject.Web.Common.WebHost;` into the NinjectWebCommon.cs after which the app started working.

**Comment by BlackPPoint** [comment]
I have done what @htuomas suggest, and when i downgrade to 3.2.2 NinjectWebCommon.cs file is created in App_Start folder. But when I then upgrade back to 3.3.4 - it disappears:(

**Comment by SkydivingAngel** [comment]
Take a look here:
https://github.com/SkydivingAngel/Ninject-WebApi-2-and-Mvc5

**Comment by scott-xu** [comment]
Source and configuration file transformations are not applied when a package is installed in a project using Package References in project files.
see https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations

**Comment by scott-xu** [comment]
You need to do it manually.

**Comment by vira1368** [comment]
To solve this problem, you can use version 3.2.1.0. if you use the following commands, `NinjectWebCommon.cs` file is added to the `App_Start` folder.

```
install-package Ninject.mvc5 -Version:3.2.1.0
install-package Ninject.Web.WebApi -Version:3.2.1.0
```

**Comment by SkydivingAngel** [comment]
Ok but why should I use an older version? Isn't it better to use the new one even if you have to write the class on your own?
Cheers

**Comment by emeol** [comment]
installing 3.2.x works just fine.

**Comment by BrunoPecanha** [comment]
I did as vira1368 wrote and it worked just fine.

**Comment by sammiullah** [comment]
@htuomas 's method worked fine for me. It might get one or two time to install and uninstall the _Ninject_ 
because for me, on first iteration it removed the Ninjectweb.common file again.. again i went to degrade the version and had the file again. and copied the file locally and upgraded it and pasted the file in App_Start folder and then there was exception as @htuomas told. then add **_using Ninject.Web.Common.WebHost;_** 

It worked for me.
Thanks

**Comment by ganesh-dks** [comment]
I had the same issue, so I excluded the NinjectWebCommon.cs and upgraded to NInject 3.3.4 and included the NinjectWebCommon.cs again. This time I got namespace reference errors, so I simply right-clicked on the erroneous class references and added their namespace. And it worked like a charm. Hope it's useful to somebody.
