### ISSUE TITLE
No support for HttpApplicationInitializationHttpModule in latest release

### ISSUE THREAD

**Issue by NimmyJohn** [ninject/Ninject.Web.Common#36]
We are using Ninject.Web.Common in our project and after updating to the latest version 3.3.0 , there are complilation issues as HttpApplicationInitializationHttpModule  is no longer available in the namespace. 
What is the alternative to binding IHttpModule to HttpApplicationInitializationHttpModule  ?

**Comment by DenisPitcher** [comment]
What was the resolution to this?
