### ISSUE TITLE
NinjectWebCommon not created after installing Ninject.Web.Common.WebHost package

### ISSUE THREAD

**Issue by smcl** [ninject/Ninject.Web.Common#38]
In the "NuGet Package" section of the wiki article "[Setting up an IIS hosted web application](https://github.com/ninject/Ninject.Web.Common/wiki/Setting-up-an-IIS-hosted-web-application)" it's suggested that after you install the WebHost package via `Install-Package Ninject.Web.Common.WebHost` then the `NinjectWebCommon` class is added to your project's App_Start directory.

However I have observed that this is not the case. I can reproduce this reliably by creating a blank WebApi application in Visual Studio 2017 (Version 15.3.2, using .NET Framework 4.7.1), then installing `Ninject.Web.Common.WebHost` either via the NuGet UI or Package Manager Console.

Is this a known issue? Would just creating the file manually accomplish the same deal, or is there some other setup related to this class involved>

Update: this was when I didn't specify any version, so version 3.3.0 was installed. When I specify 3.2.0 then the file is created.

**Comment by scott-xu** [comment]
Source and configuration file transformations are not applied when a package is installed in a project using Package References in project files.
see https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations

**Comment by scott-xu** [comment]
Looks like Microsoft starts to support source file transformation. I’ll update the package.

**Comment by chrispickford** [comment]
I've just tried installing `Ninject.Web.Common.WebHost@3.3.0` on a fresh WebAPI2 project. The NinjectWebCommon.cs file was **not** created in the App_Start directory.

Also, it would seem the documentation is out of date here:
https://github.com/ninject/Ninject.Web.Common/wiki/Setting-up-an-IIS-hosted-web-application

When copying the example NinjectWebCommon.cs source from the documation page, the static class `DynamicModuleUtility` cannot be found.
