### ISSUE TITLE
upgrade from 3.3.0.0 to 3.3.1.0 failed to recognize existing App_Start\NinjectWebCommon.cs

### ISSUE THREAD

**Issue by mmunchandersen** [ninject/Ninject.Web.Common#39]
I already had a App_Start\NinjectWebCommon.cs in my project.
Upgrading from 3.3.0.0 to 3.3.1.0 added a new App_Start\Ninject.Web.Common.cs file

Things build with both files.
I simply excluded file from visual studio project and things continues to build.

**Comment by BloodBaz** [comment]
Developer appears to have renamed the file to include dots to match assembly name (not strictly convention for C# filenamed that should match class name).  

However, the files are essentially the same so you are right - either delete the (new) `App_Start\Ninject.Web.Common.cs` file or migrate your service registrations over and delete your (old) `App_Start\NinjectWebCommon.cs` file.

**Comment by scott-xu** [comment]
fixed in release 3.3.2
